import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/AppProvider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl="/sign-in"
      appearance={{
        // variables: { // 定义全局变量，如主色调、文字颜色等
        //   colorPrimary: "#0f766e", // Tailwind's teal-700
        //   colorText: "#f8fafc",
        // },
        elements: {
          // 自定义特定 UI 元素的类名或样式
          formButtonPrimary:
            "rounded-xl bg-gradient-to-r from-purple-500 to-purple-600",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          {/* Wrap your root layout */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
